# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dlqctl < Formula
  desc "Dead-letter queue manager for SQS and Kafka"
  homepage "https://github.com/ahmad-saleem/dlqctl"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v0.1.1/dlqctl_darwin_amd64.tar.gz"
      sha256 "029ac510b002ac8aa86c7a924a5f0dbdaba9b1dbeb0b8d36e0b2eb638892f369"

      def install
        bin.install "dlqctl"
      end
    end
    on_arm do
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v0.1.1/dlqctl_darwin_arm64.tar.gz"
      sha256 "17cb87fc33c1e9aaaab59c2bf2364b93145fc05a2dca8469e06b65d5d3fea3af"

      def install
        bin.install "dlqctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v0.1.1/dlqctl_linux_amd64.tar.gz"
        sha256 "b2189f87bf4098cc51a8806b0b0aeb83319531dbfe50c2c8c08e184521b1107f"

        def install
          bin.install "dlqctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v0.1.1/dlqctl_linux_arm64.tar.gz"
        sha256 "d36e48663d581590189263865b010dd18cfc7fbabf9848fda176463d8940230d"

        def install
          bin.install "dlqctl"
        end
      end
    end
  end
end
