# This file was generated by GoReleaser. DO NOT EDIT.
cask "dlqctl" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "b537d7fed0bf6648ba7aca6ef0872d87879362c3ac025b9b40448266840ea336"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e67c7cf5c003af15382cff5f0c484a9831177487b31610bbbb065304ac8562a"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "146e35f397123e28793dd9dce70a2814d8beabefcd59da9d1280d5a2deec9013"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ca0d7c880cb8f63ca8297981491d2c6c480f43425da901b898bd163ab283fda"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_linux_arm64.tar.gz"
    end
  end

  name "dlqctl"
  desc "A CLI for operating on AWS SQS dead-letter queues: inspect stuck messages, correlate them with CloudWatch Logs, replay them back to their source queue, and export them to files."
  homepage "https://github.com/ahmad-saleem/dlqctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dlqctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dlqctl"]
    end
  end

  # No zap stanza required

end
