# This file was generated by GoReleaser. DO NOT EDIT.
cask "dlqctl" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "feee44c6876bf488f2063f9c7a597c59d74ce5e965c994a8c9a537bdf1cbe44a"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "133c46aa1161bc2b2edff9ef9f1971dcaed40ba22d221b6a2f4b1878fe2c385a"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e8ee46018cd6bf5eb43f03f0757c7507fbb97eac9e0813f14cae0c605ace2cb"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "142c9c148c6c15eb4ca9480456701c540db9dc5e49218ced6e8036ea63154b92"
      url "https://github.com/Ahmad-Saleem/dlqctl/releases/download/v#{version}/dlqctl_linux_arm64.tar.gz"
    end
  end

  name "dlqctl"
  desc "A CLI for operating on AWS SQS dead-letter queues: inspect stuck messages, correlate them with CloudWatch Logs, replay them back to their source queue, and export them to files."
  homepage "https://github.com/ahmad-saleem/dlqctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dlqctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dlqctl"]
    end
  end

  # No zap stanza required

end
